// <auto-generated />
using System;
using AIStudyPlanner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIStudyPlanner.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402042241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.AiRequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("StudyGoalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudyGoalId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AiRequestLogs");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.ProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("HoursSpent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("StudyGoalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudyTaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudyGoalId");

                    b.HasIndex("StudyTaskId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("ProgressLogs");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("ReminderDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("StudyTaskId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudyTaskId");

                    b.HasIndex("IsSent", "ReminderDateTime");

                    b.HasIndex("UserId", "ReminderDateTime");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BreakPreference")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DailyAvailableHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PreferredStudyTime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SubjectsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("StudyGoals");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("GeneratedByAI")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RawAiPrompt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("StudyGoalId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("TotalEstimatedHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudyGoalId");

                    b.HasIndex("UserId", "StudyGoalId");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ActualHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("StudyGoalId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudyPlanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Subtopic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudyPlanId");

                    b.HasIndex("StudyGoalId", "IsCompleted");

                    b.HasIndex("UserId", "TaskDate");

                    b.ToTable("StudyTasks");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.AiRequestLog", b =>
                {
                    b.HasOne("AIStudyPlanner.Api.Entities.StudyGoal", "StudyGoal")
                        .WithMany("AiRequestLogs")
                        .HasForeignKey("StudyGoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIStudyPlanner.Api.Entities.User", "User")
                        .WithMany("AiRequestLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.ProgressLog", b =>
                {
                    b.HasOne("AIStudyPlanner.Api.Entities.StudyGoal", "StudyGoal")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("StudyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIStudyPlanner.Api.Entities.StudyTask", "StudyTask")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("StudyTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIStudyPlanner.Api.Entities.User", "User")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGoal");

                    b.Navigation("StudyTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.Reminder", b =>
                {
                    b.HasOne("AIStudyPlanner.Api.Entities.StudyTask", "StudyTask")
                        .WithMany("Reminders")
                        .HasForeignKey("StudyTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AIStudyPlanner.Api.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyTask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyGoal", b =>
                {
                    b.HasOne("AIStudyPlanner.Api.Entities.User", "User")
                        .WithMany("StudyGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyPlan", b =>
                {
                    b.HasOne("AIStudyPlanner.Api.Entities.StudyGoal", "StudyGoal")
                        .WithMany("StudyPlans")
                        .HasForeignKey("StudyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIStudyPlanner.Api.Entities.User", "User")
                        .WithMany("StudyPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGoal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyTask", b =>
                {
                    b.HasOne("AIStudyPlanner.Api.Entities.StudyGoal", "StudyGoal")
                        .WithMany("StudyTasks")
                        .HasForeignKey("StudyGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIStudyPlanner.Api.Entities.StudyPlan", "StudyPlan")
                        .WithMany("Tasks")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIStudyPlanner.Api.Entities.User", "User")
                        .WithMany("StudyTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyGoal");

                    b.Navigation("StudyPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyGoal", b =>
                {
                    b.Navigation("AiRequestLogs");

                    b.Navigation("ProgressLogs");

                    b.Navigation("StudyPlans");

                    b.Navigation("StudyTasks");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyPlan", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.StudyTask", b =>
                {
                    b.Navigation("ProgressLogs");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("AIStudyPlanner.Api.Entities.User", b =>
                {
                    b.Navigation("AiRequestLogs");

                    b.Navigation("ProgressLogs");

                    b.Navigation("Reminders");

                    b.Navigation("StudyGoals");

                    b.Navigation("StudyPlans");

                    b.Navigation("StudyTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
